services:
  authen-service:
    build:
      context: ./authen-service
    container_name: authen-service
    ports:
      - "50051:50051"

  user-service:
    build:
      context: ./user-service
    container_name: user-service
    ports:
      - "50052:50052"

  gateway:
    build:
      context: ./gateway
    container_name: gateway
    ports:
      - "8080:8080"
    depends_on:
      - authen-service
      - user-service
